=== Nikita-Motko/Semantic/local_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2020 rel. 2 (x64) (http://www.altova.com) by qwerty (qwerty1) -->
<!-- W3C Schema generated by XMLSpy v2020 rel. 2 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="all">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="game" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="date" type="xs:string"/>
	<xs:element name="game">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:element ref="genre"/>
				<xs:element ref="date"/>
				<xs:element ref="rating"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="genre">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Жанр: action"/>
				<xs:enumeration value="Жанр: action, adventure"/>
				<xs:enumeration value="Жанр: action, rpg"/>
				<xs:enumeration value="Жанр: arcade"/>
				<xs:enumeration value="Жанр: rpg"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="name">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="8"/>
				<xs:enumeration value="Black Mesa"/>
				<xs:enumeration value="Divinity: Original Sin 2"/>
				<xs:enumeration value="Divinity: Original Sin 2 - Definitive Edition"/>
				<xs:enumeration value="God of War (2018)"/>
				<xs:enumeration value="Mount &amp; Blade II: Bannerlord"/>
				<xs:enumeration value="Ori and the Will of the Wisps"/>
				<xs:enumeration value="Prey (2017)"/>
				<xs:enumeration value="Red Dead Redemption 2"/>
				<xs:enumeration value="Resident Evil 2 Remake"/>
				<xs:enumeration value="Witcher 3: Wild Hunt - Complete Edition, The"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="rating">
		<xs:simpleType>
			<xs:restriction base="xs:decimal">
				<xs:enumeration value="8.6"/>
				<xs:enumeration value="8.7"/>
				<xs:enumeration value="8.8"/>
				<xs:enumeration value="8.9"/>
				<xs:enumeration value="9"/>
				<xs:enumeration value="9.1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== Nikita-Motko/Semantic/test.xml
<?xml version="1.0"?>
<all xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/1/local_schema.xsd">
	<game>
		<name>Red Dead Redemption 2</name>
		<genre>Жанр: action, adventure</genre>
		<date>Дата выхода: 26 октября 2018 г.</date>
		<rating>9.1</rating>
	</game>
	<game>
		<name>God of War (2018)</name>
		<genre>Жанр: action</genre>
		<date>Дата выхода: 20 апреля 2018 г.</date>
		<rating>9.1</rating>
	</game>
	<game>
		<name>Resident Evil 2 Remake</name>
		<genre>Жанр: action</genre>
		<date>Дата выхода: 25 января 2019 г.</date>
		<rating>9.0</rating>
	</game>
	<game>
		<name>Divinity: Original Sin 2</name>
		<genre>Жанр: rpg</genre>
		<date>Дата выхода: 14 сентября 2017 г.</date>
		<rating>9.0</rating>
	</game>
	<game>
		<name>Witcher 3: Wild Hunt - Complete Edition, The</name>
		<genre>Жанр: rpg</genre>
		<date>Дата выхода: 15 октября 2019 г.</date>
		<rating>9.0</rating>
	</game>
	<game>
		<name>Black Mesa</name>
		<genre>Жанр: action</genre>
		<date>Дата выхода: 5 марта 2020 г.</date>
		<rating>8.9</rating>
	</game>
	<game>
		<name>Divinity: Original Sin 2 - Definitive Edition</name>
		<genre>Жанр: rpg</genre>
		<date>Дата выхода: 14 сентября 2017 г.</date>
		<rating>8.8</rating>
	</game>
	<game>
		<name>Ori and the Will of the Wisps</name>
		<genre>Жанр: arcade</genre>
		<date>Дата выхода: 11 марта 2020 г.</date>
		<rating>8.7</rating>
	</game>
	<game>
		<name>Mount &amp; Blade II: Bannerlord</name>
		<genre>Жанр: action, rpg</genre>
		<date>Дата выхода: 30 марта 2020 г.</date>
		<rating>8.6</rating>
	</game>
	<game>
		<name>Prey (2017)</name>
		<genre>Жанр: action</genre>
		<date>Дата выхода: 5 мая 2017 г.</date>
		<rating>8.6</rating>
	</game>
</all>
